### ISSUE TITLE
'React is not defined' with NextJS

### ISSUE THREAD

**Issue by zackdove** [pmndrs/react-postprocessing#190]
I'm getting the following error in browser:

```caught ReferenceError: React is not defined
    at DepthOfField (index.js:209:1)
    at renderWithHooks (react-reconciler.development.js:7363:1)
    at updateForwardRef (react-reconciler.development.js:11457:1)
    at beginWork (react-reconciler.development.js:13880:1)
    at beginWork$1 (react-reconciler.development.js:19513:1)
    at performUnitOfWork (react-reconciler.development.js:18686:1)
    at workLoopSync (react-reconciler.development.js:18597:1)
    at renderRootSync (react-reconciler.development.js:18565:1)
    at recoverFromConcurrentError (react-reconciler.development.js:17948:1)
    at performConcurrentWorkOnRoot (react-reconciler.development.js:17848:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
```

Both with the latest release and the master branch.

`Package.json` :

```{
  "name": "nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@fontsource/roboto-flex": "^4.5.5",
    "@react-three/drei": "^9.66.0",
    "@react-three/fiber": "^8.12.2",
    "@react-three/offscreen": "^0.0.1",
    "@react-three/postprocessing": "github:pmndrs/react-postprocessing#master",
    "eslint": "8.37.0",
    "eslint-config-next": "13.3.0",
    "framer-motion": "^10.12.4",
    "lamina": "^1.1.23",
    "next": "13.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-draggable": "^4.4.5",
    "react-slick": "^0.29.0",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.3.10",
    "three": "^0.151.3"
  },
  "devDependencies": {
    "@types/node": "18.15.13",
    "@types/styled-components": "^5.1.26"
  }
}
```

**Comment by talentlessguy** [comment]
I might need to tweak tsconfig and rollup config, probably jsx isn't generating properly

hold on for a few mins i'll fix it

**Comment by talentlessguy** [comment]
does it work now? @zackdove

**Comment by zackdove** [comment]
Getting the same error unfortunately

**Comment by talentlessguy** [comment]
@zackdove what's your next config

**Comment by zackdove** [comment]
I fixed this by adding:

```
import React from "react";
window.React = React;
```

To my component containing the `Canvas` and `EffectComposer` components. There's probably a much better way to do this.
