### ISSUE TITLE
Invalid value used as weak map key in postprocessing

### ISSUE THREAD

**Issue by KrzysztofSieczkiewicz** [pmndrs/react-postprocessing#279]
When changing DepthOfField focal length or focus distance using slider
I'm getting browser blackout and shortly after error message:
`Invalid value used as weak map key
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Object.drawBuffers (http://localhost:3000/static/js/bundle.js:113367:28)
    at WebGLRenderer.setRenderTarget (http://localhost:3000/static/js/bundle.js:117814:15)
    at ShaderPass.render (http://localhost:3000/static/js/bundle.js:26281:14)
    at DepthOfFieldEffect.update (http://localhost:3000/static/js/bundle.js:28496:18)
    at EffectPass.render (http://localhost:3000/static/js/bundle.js:25266:14)
    at EffectComposer.render (http://localhost:3000/static/js/bundle.js:26746:14)
    at Object.current (http://localhost:3000/static/js/bundle.js:89791:16)
    at render$1 (http://localhost:3000/static/js/bundle.js:8530:22)
    at loop (http://localhost:3000/static/js/bundle.js:8557:19)`

**Comment by kvvasuu** [comment]
Can't reproduce on the current 3.0.5. Closing - please reopen with a fresh repro if it's still happening.
